#![allow(unused_imports, dead_code, clippy::all, warnings)]
// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod dx_icon {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum LicenseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct License<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for License<'a> {
  type Inner = License<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> License<'a> {
  pub const VT_TITLE: flatbuffers::VOffsetT = 4;
  pub const VT_SPDX: flatbuffers::VOffsetT = 6;
  pub const VT_URL: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    License { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LicenseArgs<'args>
  ) -> flatbuffers::WIPOffset<License<'bldr>> {
    let mut builder = LicenseBuilder::new(_fbb);
    if let Some(x) = args.url { builder.add_url(x); }
    if let Some(x) = args.spdx { builder.add_spdx(x); }
    if let Some(x) = args.title { builder.add_title(x); }
    builder.finish()
  }


  #[inline]
  pub fn title(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(License::VT_TITLE, None)}
  }
  #[inline]
  pub fn spdx(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(License::VT_SPDX, None)}
  }
  #[inline]
  pub fn url(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(License::VT_URL, None)}
  }
}

impl flatbuffers::Verifiable for License<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("title", Self::VT_TITLE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("spdx", Self::VT_SPDX, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("url", Self::VT_URL, false)?
     .finish();
    Ok(())
  }
}
pub struct LicenseArgs<'a> {
    pub title: Option<flatbuffers::WIPOffset<&'a str>>,
    pub spdx: Option<flatbuffers::WIPOffset<&'a str>>,
    pub url: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for LicenseArgs<'a> {
  #[inline]
  fn default() -> Self {
    LicenseArgs {
      title: None,
      spdx: None,
      url: None,
    }
  }
}

pub struct LicenseBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> LicenseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_title(&mut self, title: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(License::VT_TITLE, title);
  }
  #[inline]
  pub fn add_spdx(&mut self, spdx: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(License::VT_SPDX, spdx);
  }
  #[inline]
  pub fn add_url(&mut self, url: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(License::VT_URL, url);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> LicenseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LicenseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<License<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for License<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("License");
      ds.field("title", &self.title());
      ds.field("spdx", &self.spdx());
      ds.field("url", &self.url());
      ds.finish()
  }
}
pub enum AuthorOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Author<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Author<'a> {
  type Inner = Author<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Author<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_URL: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Author { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AuthorArgs<'args>
  ) -> flatbuffers::WIPOffset<Author<'bldr>> {
    let mut builder = AuthorBuilder::new(_fbb);
    if let Some(x) = args.url { builder.add_url(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Author::VT_NAME, None)}
  }
  #[inline]
  pub fn url(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Author::VT_URL, None)}
  }
}

impl flatbuffers::Verifiable for Author<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("url", Self::VT_URL, false)?
     .finish();
    Ok(())
  }
}
pub struct AuthorArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub url: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for AuthorArgs<'a> {
  #[inline]
  fn default() -> Self {
    AuthorArgs {
      name: None,
      url: None,
    }
  }
}

pub struct AuthorBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> AuthorBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Author::VT_NAME, name);
  }
  #[inline]
  pub fn add_url(&mut self, url: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Author::VT_URL, url);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> AuthorBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AuthorBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Author<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Author<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Author");
      ds.field("name", &self.name());
      ds.field("url", &self.url());
      ds.finish()
  }
}
pub enum IconInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IconInfo<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for IconInfo<'a> {
  type Inner = IconInfo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> IconInfo<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_TOTAL: flatbuffers::VOffsetT = 6;
  pub const VT_VERSION: flatbuffers::VOffsetT = 8;
  pub const VT_AUTHOR: flatbuffers::VOffsetT = 10;
  pub const VT_LICENSE: flatbuffers::VOffsetT = 12;
  pub const VT_HEIGHT: flatbuffers::VOffsetT = 14;
  pub const VT_CATEGORY: flatbuffers::VOffsetT = 16;
  pub const VT_PALETTE: flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    IconInfo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args IconInfoArgs<'args>
  ) -> flatbuffers::WIPOffset<IconInfo<'bldr>> {
    let mut builder = IconInfoBuilder::new(_fbb);
    if let Some(x) = args.category { builder.add_category(x); }
    builder.add_height(args.height);
    if let Some(x) = args.license { builder.add_license(x); }
    if let Some(x) = args.author { builder.add_author(x); }
    if let Some(x) = args.version { builder.add_version(x); }
    builder.add_total(args.total);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_palette(args.palette);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(IconInfo::VT_NAME, None)}
  }
  #[inline]
  pub fn total(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(IconInfo::VT_TOTAL, Some(0)).unwrap()}
  }
  #[inline]
  pub fn version(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(IconInfo::VT_VERSION, None)}
  }
  #[inline]
  pub fn author(&self) -> Option<Author<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<Author>>(IconInfo::VT_AUTHOR, None)}
  }
  #[inline]
  pub fn license(&self) -> Option<License<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<License>>(IconInfo::VT_LICENSE, None)}
  }
  #[inline]
  pub fn height(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(IconInfo::VT_HEIGHT, Some(16)).unwrap()}
  }
  #[inline]
  pub fn category(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(IconInfo::VT_CATEGORY, None)}
  }
  #[inline]
  pub fn palette(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(IconInfo::VT_PALETTE, Some(false)).unwrap()}
  }
}

impl flatbuffers::Verifiable for IconInfo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<u32>("total", Self::VT_TOTAL, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("version", Self::VT_VERSION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<Author>>("author", Self::VT_AUTHOR, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<License>>("license", Self::VT_LICENSE, false)?
     .visit_field::<u32>("height", Self::VT_HEIGHT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("category", Self::VT_CATEGORY, false)?
     .visit_field::<bool>("palette", Self::VT_PALETTE, false)?
     .finish();
    Ok(())
  }
}
pub struct IconInfoArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub total: u32,
    pub version: Option<flatbuffers::WIPOffset<&'a str>>,
    pub author: Option<flatbuffers::WIPOffset<Author<'a>>>,
    pub license: Option<flatbuffers::WIPOffset<License<'a>>>,
    pub height: u32,
    pub category: Option<flatbuffers::WIPOffset<&'a str>>,
    pub palette: bool,
}
impl<'a> Default for IconInfoArgs<'a> {
  #[inline]
  fn default() -> Self {
    IconInfoArgs {
      name: None,
      total: 0,
      version: None,
      author: None,
      license: None,
      height: 16,
      category: None,
      palette: false,
    }
  }
}

pub struct IconInfoBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> IconInfoBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IconInfo::VT_NAME, name);
  }
  #[inline]
  pub fn add_total(&mut self, total: u32) {
    self.fbb_.push_slot::<u32>(IconInfo::VT_TOTAL, total, 0);
  }
  #[inline]
  pub fn add_version(&mut self, version: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IconInfo::VT_VERSION, version);
  }
  #[inline]
  pub fn add_author(&mut self, author: flatbuffers::WIPOffset<Author<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Author>>(IconInfo::VT_AUTHOR, author);
  }
  #[inline]
  pub fn add_license(&mut self, license: flatbuffers::WIPOffset<License<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<License>>(IconInfo::VT_LICENSE, license);
  }
  #[inline]
  pub fn add_height(&mut self, height: u32) {
    self.fbb_.push_slot::<u32>(IconInfo::VT_HEIGHT, height, 16);
  }
  #[inline]
  pub fn add_category(&mut self, category: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IconInfo::VT_CATEGORY, category);
  }
  #[inline]
  pub fn add_palette(&mut self, palette: bool) {
    self.fbb_.push_slot::<bool>(IconInfo::VT_PALETTE, palette, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> IconInfoBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    IconInfoBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<IconInfo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for IconInfo<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("IconInfo");
      ds.field("name", &self.name());
      ds.field("total", &self.total());
      ds.field("version", &self.version());
      ds.field("author", &self.author());
      ds.field("license", &self.license());
      ds.field("height", &self.height());
      ds.field("category", &self.category());
      ds.field("palette", &self.palette());
      ds.finish()
  }
}
pub enum IconOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Icon<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Icon<'a> {
  type Inner = Icon<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Icon<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_BODY: flatbuffers::VOffsetT = 6;
  pub const VT_WIDTH: flatbuffers::VOffsetT = 8;
  pub const VT_HEIGHT: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Icon { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args IconArgs<'args>
  ) -> flatbuffers::WIPOffset<Icon<'bldr>> {
    let mut builder = IconBuilder::new(_fbb);
    builder.add_height(args.height);
    builder.add_width(args.width);
    if let Some(x) = args.body { builder.add_body(x); }
    if let Some(x) = args.id { builder.add_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Icon::VT_ID, None).unwrap()}
  }
  #[inline]
  pub fn key_compare_less_than(&self, o: &Icon) -> bool {
    self.id() < o.id()
  }

  #[inline]
  pub fn key_compare_with_value(&self, val: & str) -> ::core::cmp::Ordering {
    let key = self.id();
    key.cmp(val)
  }
  #[inline]
  pub fn body(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Icon::VT_BODY, None)}
  }
  #[inline]
  pub fn width(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Icon::VT_WIDTH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn height(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Icon::VT_HEIGHT, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Icon<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("body", Self::VT_BODY, false)?
     .visit_field::<u32>("width", Self::VT_WIDTH, false)?
     .visit_field::<u32>("height", Self::VT_HEIGHT, false)?
     .finish();
    Ok(())
  }
}
pub struct IconArgs<'a> {
    pub id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub body: Option<flatbuffers::WIPOffset<&'a str>>,
    pub width: u32,
    pub height: u32,
}
impl<'a> Default for IconArgs<'a> {
  #[inline]
  fn default() -> Self {
    IconArgs {
      id: None, // required field
      body: None,
      width: 0,
      height: 0,
    }
  }
}

pub struct IconBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> IconBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Icon::VT_ID, id);
  }
  #[inline]
  pub fn add_body(&mut self, body: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Icon::VT_BODY, body);
  }
  #[inline]
  pub fn add_width(&mut self, width: u32) {
    self.fbb_.push_slot::<u32>(Icon::VT_WIDTH, width, 0);
  }
  #[inline]
  pub fn add_height(&mut self, height: u32) {
    self.fbb_.push_slot::<u32>(Icon::VT_HEIGHT, height, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> IconBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    IconBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Icon<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Icon::VT_ID,"id");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Icon<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Icon");
      ds.field("id", &self.id());
      ds.field("body", &self.body());
      ds.field("width", &self.width());
      ds.field("height", &self.height());
      ds.finish()
  }
}
pub enum IconSetOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IconSet<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for IconSet<'a> {
  type Inner = IconSet<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> IconSet<'a> {
  pub const VT_PREFIX: flatbuffers::VOffsetT = 4;
  pub const VT_INFO: flatbuffers::VOffsetT = 6;
  pub const VT_ICONS: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    IconSet { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args IconSetArgs<'args>
  ) -> flatbuffers::WIPOffset<IconSet<'bldr>> {
    let mut builder = IconSetBuilder::new(_fbb);
    if let Some(x) = args.icons { builder.add_icons(x); }
    if let Some(x) = args.info { builder.add_info(x); }
    if let Some(x) = args.prefix { builder.add_prefix(x); }
    builder.finish()
  }


  #[inline]
  pub fn prefix(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(IconSet::VT_PREFIX, None)}
  }
  #[inline]
  pub fn info(&self) -> Option<IconInfo<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<IconInfo>>(IconSet::VT_INFO, None)}
  }
  #[inline]
  pub fn icons(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Icon<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Icon>>>>(IconSet::VT_ICONS, None)}
  }
}

impl flatbuffers::Verifiable for IconSet<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("prefix", Self::VT_PREFIX, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<IconInfo>>("info", Self::VT_INFO, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Icon>>>>("icons", Self::VT_ICONS, false)?
     .finish();
    Ok(())
  }
}
pub struct IconSetArgs<'a> {
    pub prefix: Option<flatbuffers::WIPOffset<&'a str>>,
    pub info: Option<flatbuffers::WIPOffset<IconInfo<'a>>>,
    pub icons: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Icon<'a>>>>>,
}
impl<'a> Default for IconSetArgs<'a> {
  #[inline]
  fn default() -> Self {
    IconSetArgs {
      prefix: None,
      info: None,
      icons: None,
    }
  }
}

pub struct IconSetBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> IconSetBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_prefix(&mut self, prefix: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IconSet::VT_PREFIX, prefix);
  }
  #[inline]
  pub fn add_info(&mut self, info: flatbuffers::WIPOffset<IconInfo<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<IconInfo>>(IconSet::VT_INFO, info);
  }
  #[inline]
  pub fn add_icons(&mut self, icons: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Icon<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(IconSet::VT_ICONS, icons);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> IconSetBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    IconSetBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<IconSet<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for IconSet<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("IconSet");
      ds.field("prefix", &self.prefix());
      ds.field("info", &self.info());
      ds.field("icons", &self.icons());
      ds.finish()
  }
}
pub enum SvglIconOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SvglIcon<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SvglIcon<'a> {
  type Inner = SvglIcon<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> SvglIcon<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_FILENAME: flatbuffers::VOffsetT = 6;
  pub const VT_SVG_CONTENT: flatbuffers::VOffsetT = 8;
  pub const VT_VIEWBOX: flatbuffers::VOffsetT = 10;
  pub const VT_WIDTH: flatbuffers::VOffsetT = 12;
  pub const VT_HEIGHT: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SvglIcon { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SvglIconArgs<'args>
  ) -> flatbuffers::WIPOffset<SvglIcon<'bldr>> {
    let mut builder = SvglIconBuilder::new(_fbb);
    builder.add_height(args.height);
    builder.add_width(args.width);
    if let Some(x) = args.viewbox { builder.add_viewbox(x); }
    if let Some(x) = args.svg_content { builder.add_svg_content(x); }
    if let Some(x) = args.filename { builder.add_filename(x); }
    if let Some(x) = args.id { builder.add_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SvglIcon::VT_ID, None).unwrap()}
  }
  #[inline]
  pub fn key_compare_less_than(&self, o: &SvglIcon) -> bool {
    self.id() < o.id()
  }

  #[inline]
  pub fn key_compare_with_value(&self, val: & str) -> ::core::cmp::Ordering {
    let key = self.id();
    key.cmp(val)
  }
  #[inline]
  pub fn filename(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SvglIcon::VT_FILENAME, None)}
  }
  #[inline]
  pub fn svg_content(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SvglIcon::VT_SVG_CONTENT, None)}
  }
  #[inline]
  pub fn viewbox(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SvglIcon::VT_VIEWBOX, None)}
  }
  #[inline]
  pub fn width(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(SvglIcon::VT_WIDTH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn height(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(SvglIcon::VT_HEIGHT, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for SvglIcon<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("filename", Self::VT_FILENAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("svg_content", Self::VT_SVG_CONTENT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("viewbox", Self::VT_VIEWBOX, false)?
     .visit_field::<u32>("width", Self::VT_WIDTH, false)?
     .visit_field::<u32>("height", Self::VT_HEIGHT, false)?
     .finish();
    Ok(())
  }
}
pub struct SvglIconArgs<'a> {
    pub id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub filename: Option<flatbuffers::WIPOffset<&'a str>>,
    pub svg_content: Option<flatbuffers::WIPOffset<&'a str>>,
    pub viewbox: Option<flatbuffers::WIPOffset<&'a str>>,
    pub width: u32,
    pub height: u32,
}
impl<'a> Default for SvglIconArgs<'a> {
  #[inline]
  fn default() -> Self {
    SvglIconArgs {
      id: None, // required field
      filename: None,
      svg_content: None,
      viewbox: None,
      width: 0,
      height: 0,
    }
  }
}

pub struct SvglIconBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SvglIconBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SvglIcon::VT_ID, id);
  }
  #[inline]
  pub fn add_filename(&mut self, filename: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SvglIcon::VT_FILENAME, filename);
  }
  #[inline]
  pub fn add_svg_content(&mut self, svg_content: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SvglIcon::VT_SVG_CONTENT, svg_content);
  }
  #[inline]
  pub fn add_viewbox(&mut self, viewbox: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SvglIcon::VT_VIEWBOX, viewbox);
  }
  #[inline]
  pub fn add_width(&mut self, width: u32) {
    self.fbb_.push_slot::<u32>(SvglIcon::VT_WIDTH, width, 0);
  }
  #[inline]
  pub fn add_height(&mut self, height: u32) {
    self.fbb_.push_slot::<u32>(SvglIcon::VT_HEIGHT, height, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SvglIconBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SvglIconBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SvglIcon<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, SvglIcon::VT_ID,"id");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SvglIcon<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SvglIcon");
      ds.field("id", &self.id());
      ds.field("filename", &self.filename());
      ds.field("svg_content", &self.svg_content());
      ds.field("viewbox", &self.viewbox());
      ds.field("width", &self.width());
      ds.field("height", &self.height());
      ds.finish()
  }
}
pub enum SvglCollectionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SvglCollection<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SvglCollection<'a> {
  type Inner = SvglCollection<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> SvglCollection<'a> {
  pub const VT_ICONS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SvglCollection { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SvglCollectionArgs<'args>
  ) -> flatbuffers::WIPOffset<SvglCollection<'bldr>> {
    let mut builder = SvglCollectionBuilder::new(_fbb);
    if let Some(x) = args.icons { builder.add_icons(x); }
    builder.finish()
  }


  #[inline]
  pub fn icons(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<SvglIcon<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<SvglIcon>>>>(SvglCollection::VT_ICONS, None)}
  }
}

impl flatbuffers::Verifiable for SvglCollection<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<SvglIcon>>>>("icons", Self::VT_ICONS, false)?
     .finish();
    Ok(())
  }
}
pub struct SvglCollectionArgs<'a> {
    pub icons: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<SvglIcon<'a>>>>>,
}
impl<'a> Default for SvglCollectionArgs<'a> {
  #[inline]
  fn default() -> Self {
    SvglCollectionArgs {
      icons: None,
    }
  }
}

pub struct SvglCollectionBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SvglCollectionBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_icons(&mut self, icons: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<SvglIcon<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SvglCollection::VT_ICONS, icons);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SvglCollectionBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SvglCollectionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SvglCollection<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SvglCollection<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SvglCollection");
      ds.field("icons", &self.icons());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `IconSet`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_icon_set_unchecked`.
pub fn root_as_icon_set(buf: &[u8]) -> Result<IconSet, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<IconSet>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `IconSet` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_icon_set_unchecked`.
pub fn size_prefixed_root_as_icon_set(buf: &[u8]) -> Result<IconSet, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<IconSet>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `IconSet` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_icon_set_unchecked`.
pub fn root_as_icon_set_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<IconSet<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<IconSet<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `IconSet` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_icon_set_unchecked`.
pub fn size_prefixed_root_as_icon_set_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<IconSet<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<IconSet<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a IconSet and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `IconSet`.
pub unsafe fn root_as_icon_set_unchecked(buf: &[u8]) -> IconSet {
  flatbuffers::root_unchecked::<IconSet>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed IconSet and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `IconSet`.
pub unsafe fn size_prefixed_root_as_icon_set_unchecked(buf: &[u8]) -> IconSet {
  flatbuffers::size_prefixed_root_unchecked::<IconSet>(buf)
}
#[inline]
pub fn finish_icon_set_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<IconSet<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_icon_set_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<IconSet<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod dx_icon

